/**
 * Blog Resolver
 * ─────────────
 * Merges static blogPosts + auto-generated + programmatic posts into a single pool.
 */

import { blogPosts, type BlogPost } from '@/data/blogData';
import { getAutoGeneratedBlogPosts } from '@/lib/autoBlogs';
import { getAllProgrammaticBlogPosts } from '@/lib/programmaticBlogs';

/** All posts — programmatic first, then auto-generated, then static, deduplicated by slug. */
export function getAllPosts(): BlogPost[] {
  const programmatic = getAllProgrammaticBlogPosts();
  const autoPosts = getAutoGeneratedBlogPosts();
  const slugSet = new Set<string>();
  const result: BlogPost[] = [];

  for (const p of programmatic) {
    if (!slugSet.has(p.slug)) {
      slugSet.add(p.slug);
      result.push(p);
    }
  }
  for (const p of autoPosts) {
    if (!slugSet.has(p.slug)) {
      slugSet.add(p.slug);
      result.push(p);
    }
  }
  for (const p of blogPosts) {
    if (!slugSet.has(p.slug)) {
      slugSet.add(p.slug);
      result.push(p);
    }
  }
  return result;
}

/** Find a single post by slug across all sources. */
export function resolvePostBySlug(slug: string): BlogPost | undefined {
  return getAllPosts().find(p => p.slug === slug);
}

/** Related posts across all sources. */
export function resolveRelatedPosts(currentPost: BlogPost, limit = 3): BlogPost[] {
  return getAllPosts()
    .filter(
      p =>
        p.slug !== currentPost.slug &&
        (p.category === currentPost.category ||
          p.tags.some(tag => currentPost.tags.includes(tag))),
    )
    .slice(0, limit);
}

/** Get all blog slugs (for sitemap) */
export function getAllBlogSlugs(): string[] {
  return getAllPosts().map(p => `blog/${p.slug}`);
}
