/**
 * Blog Resolver
 * ─────────────
 * Merges static blogPosts + auto-generated + programmatic posts into a single pool.
 * 
 * IMPORTANT: Uses lazy evaluation to avoid generating all 7,000+ blog posts
 * at module import time, which would cause 20MB+ ISR fallback failures on Vercel.
 */

import { blogPosts, type BlogPost } from '@/data/blogData';
import { getAutoGeneratedBlogPosts } from '@/lib/autoBlogs';
import { getExamEventBlogPosts } from '@/lib/examEventBlogs';
import { improveBlogContent } from '@/lib/blogQuality';

/** Lazy-loaded programmatic posts — only generated when first accessed */
let _programmaticPosts: BlogPost[] | null = null;
let _allPostsCache: BlogPost[] | null = null;
function getProgrammaticPosts(): BlogPost[] {
  if (!_programmaticPosts) {
    // Dynamic import workaround: use require-style to avoid top-level import
    // that pulls the entire 20MB content into the module graph at build time.
    // Intentionally synchronous require so getProgrammaticPosts() stays sync.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { getAllProgrammaticBlogPosts } = require('@/lib/programmaticBlogs');
    _programmaticPosts = getAllProgrammaticBlogPosts();
  }
  return _programmaticPosts;
}

/** All posts — programmatic first, then auto-generated, then static, deduplicated by slug. */
export function getAllPosts(): BlogPost[] {
  if (_allPostsCache) return _allPostsCache;

  const programmatic = getProgrammaticPosts();
  const autoPosts = getAutoGeneratedBlogPosts();
  const examEventPosts = getExamEventBlogPosts();
  const slugSet = new Set<string>();
  const result: BlogPost[] = [];

  // Exam event posts get highest priority (most timely)
  for (const p of examEventPosts) {
    if (!slugSet.has(p.slug)) {
      slugSet.add(p.slug);
      result.push(p);
    }
  }
  for (const p of programmatic) {
    if (!slugSet.has(p.slug)) {
      slugSet.add(p.slug);
      result.push(p);
    }
  }
  for (const p of autoPosts) {
    if (!slugSet.has(p.slug)) {
      slugSet.add(p.slug);
      result.push(p);
    }
  }
  for (const p of blogPosts) {
    if (!slugSet.has(p.slug)) {
      slugSet.add(p.slug);
      result.push(p);
    }
  }

  _allPostsCache = result.map(improveBlogContent);
  return _allPostsCache;
}

/** Get all posts WITHOUT content — for listing pages (avoids 20MB payload) */
export function getAllPostsSummary(): Omit<BlogPost, 'content'>[] {
  return getAllPosts().map(({ content, ...rest }) => rest);
}

/** Find a single post by slug across all sources. */
export function resolvePostBySlug(slug: string): BlogPost | undefined {
  return getAllPosts().find(p => p.slug === slug);
}

/** Related posts across all sources. */
export function resolveRelatedPosts(currentPost: BlogPost, limit = 3): BlogPost[] {
  return getAllPosts()
    .filter(
      p =>
        p.slug !== currentPost.slug &&
        (p.category === currentPost.category ||
          p.tags.some(tag => currentPost.tags.includes(tag))),
    )
    .slice(0, limit);
}

/** Get all blog slugs (for sitemap) */
export function getAllBlogSlugs(): string[] {
  return getAllPosts().map(p => `blog/${p.slug}`);
}
