/**
 * Blog Resolver
 * ─────────────
 * Merges static blogPosts + auto-generated posts into a single pool.
 * Kept separate from blogData.ts to avoid circular imports
 * (autoBlogs.ts imports types from blogData.ts).
 */

import { blogPosts, type BlogPost } from '@/data/blogData';
import { getAutoGeneratedBlogPosts } from '@/lib/autoBlogs';

/** All posts — auto-generated first, then static, deduplicated by slug. */
export function getAllPosts(): BlogPost[] {
  const autoPosts = getAutoGeneratedBlogPosts();
  const slugSet = new Set(autoPosts.map(p => p.slug));
  const staticFiltered = blogPosts.filter(p => !slugSet.has(p.slug));
  return [...autoPosts, ...staticFiltered];
}

/** Find a single post by slug across all sources. */
export function resolvePostBySlug(slug: string): BlogPost | undefined {
  return getAllPosts().find(p => p.slug === slug);
}

/** Related posts across all sources. */
export function resolveRelatedPosts(currentPost: BlogPost, limit = 3): BlogPost[] {
  return getAllPosts()
    .filter(
      p =>
        p.slug !== currentPost.slug &&
        (p.category === currentPost.category ||
          p.tags.some(tag => currentPost.tags.includes(tag))),
    )
    .slice(0, limit);
}
