/**
 * Content Freshness Utility — honest, git-derived dates.
 *
 * Replaces the previous auto-bumping implementation that returned a fresh
 * date every day regardless of whether content actually changed. That kind
 * of fake-freshness signal is exactly what Google's spam updates target.
 *
 * Now: every date this module returns is anchored to the last real git
 * commit on the source file that drives the page. Dates only advance when
 * a content commit advances them. Stable between builds with no content
 * changes — which is what crawlers expect.
 *
 * Generated data lives in src/lib/freshnessData.generated.ts and is
 * regenerated by scripts/gen-freshness-data.mjs at build time.
 */

import { SOURCE_LAST_MODIFIED, BUILD_BASE_DATE } from './freshnessData.generated';

export { getExamYear as getCurrentExamYear } from './examYears';

/* ── Map slug patterns → the source file whose git history reflects that
       page's actual content. Most-specific first, fallthrough to default. ── */
const SLUG_SOURCE_MAP: Array<{ test: (s: string) => boolean; source: string }> = [
  // Chapter / subject / topic pages
  { test: (s) => /^(jee|neet)-(physics|chemistry|mathematics|biology)-/.test(s), source: 'src/data/chapterData.ts' },
  // City pages
  { test: (s) => s.includes('coaching-in-'), source: 'src/data/cityData.ts' },
  // State pages
  { test: (s) => s.startsWith('online-coaching-'), source: 'src/data/stateLandingPages.ts' },
  // Exam info pages
  { test: (s) => /-(syllabus|exam-pattern|cutoff|important-dates|eligibility|result|registration|admit-card|answer-key|counselling)-\d{4}$/.test(s), source: 'src/data/examInfoData.ts' },
  // Difference-between pages
  { test: (s) => s.startsWith('difference-between-'), source: 'src/data/differenceBetweenData.ts' },
  // Formula sheets
  { test: (s) => s.endsWith('-formulas'), source: 'src/data/formulaSheetData.ts' },
  // Comparison pages
  { test: (s) => s.startsWith('mindpeak-vs-'), source: 'src/data/comparisonData.ts' },
  // Course pages
  { test: (s) => s.startsWith('course/'), source: 'src/data/coursesData.ts' },
];

/**
 * Returns the last-modified date (YYYY-MM-DD) for a page slug, derived
 * from the git history of the source file that owns its content. Falls
 * back to BUILD_BASE_DATE (the most recent content commit across all
 * tracked sources) when no specific mapping matches.
 *
 * Stability: identical input → identical output until the underlying
 * source file is committed. No daily auto-bump. No today-fallback.
 */
export function getLastUpdated(pageSlug: string): string {
  const slug = pageSlug.replace(/^\//, '');
  for (const rule of SLUG_SOURCE_MAP) {
    if (rule.test(slug)) {
      const date = SOURCE_LAST_MODIFIED[rule.source];
      if (date) return date;
    }
  }
  // Fallback: most recent commit across all sources. Honest because it
  // never returns a date past the actual most-recent content change.
  return BUILD_BASE_DATE;
}

/** Formatted "Month Day, Year" string for display. */
export function getFormattedLastUpdated(pageSlug: string): string {
  const dateStr = getLastUpdated(pageSlug);
  return new Date(dateStr).toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

/** True if the page slug belongs to a content-heavy section worth showing a freshness signal on. */
export function shouldShowFreshnessSignal(pageSlug: string): boolean {
  const contentPages = [
    'coaching', 'blog', 'location', 'subject', 'chapter', 'topic',
    'comparison', 'formula', 'rank-predictor', 'kota-alternative',
    'online-vs-offline', 'practice', 'pyq', 'study-guide', 'preparation',
    'crash-course', 'dropper', 'foundation', 'bitsat', 'cuet', 'wbjee',
    'mht-cet', 'kvpy', 'isi', 'comedk', 'viteee', 'srmjeee', 'kcet',
    'eamcet', 'olympiad',
  ];
  return contentPages.some((p) => pageSlug.includes(p));
}

/** Direct access to a tracked source file's last-modified date — used by blog metadata and JSON-LD. */
export function getSourceLastModified(sourceFile: string): string {
  return SOURCE_LAST_MODIFIED[sourceFile] ?? BUILD_BASE_DATE;
}

export { BUILD_BASE_DATE };
