// AUTO-GENERATED by scripts/gen-freshness-data.mjs — do not edit by hand.
// Regenerated on every `npm run build` from real git log timestamps.
// Editing this file directly will fake freshness signals — use a real
// content commit instead.

export const SOURCE_LAST_MODIFIED: Readonly<Record<string, string>> = {
  "src/data/blogData.ts": "2026-03-13",
  "src/data/chapterData.ts": "2026-03-08",
  "src/data/seoPageData.ts": "2026-05-11",
  "src/data/stateLandingPages.ts": "2026-05-11",
  "src/data/cityData.ts": "2026-03-15",
  "src/data/cityUniqueContent.ts": "2026-03-11",
  "src/data/examInfoData.ts": "2026-03-08",
  "src/data/differenceBetweenData.ts": "2026-03-08",
  "src/data/counsellingData.ts": "2026-03-08",
  "src/data/formulaSheetData.ts": "2026-03-08",
  "src/data/comparisonData.ts": "2026-03-08",
  "src/data/coursesData.ts": "2026-03-15",
  "src/lib/programmaticBlogs.ts": "2026-04-08",
  "src/lib/examEventBlogs.ts": "2026-03-15"
} as const;

export const BUILD_BASE_DATE = '2026-05-11';
